# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Python/Desktop/sdup/simple_speech_recognition/project_final/project_final.srcs/sources_1/bd/design_final/ip/design_final_xbar_0/design_final_xbar_0.xci
# IP: The module: 'design_final_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Python/Desktop/sdup/simple_speech_recognition/project_final/project_final.gen/sources_1/bd/design_final/ip/design_final_xbar_0/design_final_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_final_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Python/Desktop/sdup/simple_speech_recognition/project_final/project_final.srcs/sources_1/bd/design_final/ip/design_final_xbar_0/design_final_xbar_0.xci
# IP: The module: 'design_final_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Python/Desktop/sdup/simple_speech_recognition/project_final/project_final.gen/sources_1/bd/design_final/ip/design_final_xbar_0/design_final_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_final_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
