#!/usr/bin/env python3
"""
wav_to_mem.py
=============
Convert a .wav file (16 kHz, mono, 16-bit PCM) into a Vivado-compatible
.mem file in Q1.15 fixed-point format (one 16-bit signed sample per line,
hexadecimal, two's complement).

The file is consumed by `bram_stream_source.sv` via `$readmemh`.

Usage:
    python tools/wav_to_mem.py data/on.wav data/samples.mem
    python tools/wav_to_mem.py data/on.wav data/samples.mem --max-samples 16384
"""

import argparse
import sys
from pathlib import Path

import numpy as np
import soundfile as sf

TARGET_FS = 16_000


def load_and_normalize(path: str) -> np.ndarray:
    data, fs = sf.read(path, dtype="float32", always_2d=False)
    if data.ndim > 1:
        data = data.mean(axis=1)
    if fs != TARGET_FS:
        raise ValueError(
            f"Wymagana fs={TARGET_FS} Hz, otrzymano {fs} Hz. "
            "Przepróbkuj nagranie (np. sox/librosa) przed konwersją."
        )
    peak = float(np.max(np.abs(data))) if data.size else 1.0
    if peak > 0:
        data = (data / peak) * 0.99
    return data.astype(np.float32)


def to_q15_hex(samples: np.ndarray) -> list[str]:
    """Konwersja float [-1, 1) -> Q1.15 hex (two's complement)."""
    scaled = np.clip(np.round(samples * (1 << 15)),
                     -(1 << 15), (1 << 15) - 1).astype(np.int32)
    out = []
    for v in scaled:
        if v < 0:
            v = (1 << 16) + int(v)
        out.append(f"{int(v) & 0xFFFF:04x}")
    return out


def write_mem(hex_lines: list[str], path: str) -> None:
    with open(path, "w", encoding="ascii") as f:
        f.write("// Generated by tools/wav_to_mem.py (Q1.15, 16-bit signed)\n")
        f.write(f"// {len(hex_lines)} samples, fs={TARGET_FS} Hz\n")
        for h in hex_lines:
            f.write(h + "\n")


def main() -> int:
    p = argparse.ArgumentParser(description="WAV -> .mem (Q1.15)")
    p.add_argument("input", help="ścieżka do .wav (16 kHz, mono)")
    p.add_argument("output", help="ścieżka wyjściowa .mem")
    p.add_argument("--max-samples", type=int, default=16_384,
                   help="liczba próbek (zero-pad lub przyciecie, default 16384)")
    args = p.parse_args()

    samples = load_and_normalize(args.input)
    print(f"Wczytano {args.input}: {len(samples)} próbek @ {TARGET_FS} Hz")

    if args.max_samples:
        if len(samples) > args.max_samples:
            samples = samples[: args.max_samples]
        elif len(samples) < args.max_samples:
            pad = np.zeros(args.max_samples - len(samples), dtype=samples.dtype)
            samples = np.concatenate([samples, pad])

    hex_lines = to_q15_hex(samples)
    Path(args.output).parent.mkdir(parents=True, exist_ok=True)
    write_mem(hex_lines, args.output)
    print(f"Zapisano {len(hex_lines)} próbek do {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
