# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Python/Desktop/sdup/simple_speech_recognition/project_final/design_ssr_zedboard_5btn.xdc

# Block Designs: bd/design_final/design_final.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_final || ORIG_REF_NAME==design_final} -quiet] -quiet

# IP: bd/design_final/ip/design_final_top_ssr_0_0/design_final_top_ssr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_final_top_ssr_0_0 || ORIG_REF_NAME==design_final_top_ssr_0_0} -quiet] -quiet

# IP: bd/design_final/ip/design_final_processing_system7_0_0/design_final_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_final_processing_system7_0_0 || ORIG_REF_NAME==design_final_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_final/ip/design_final_axi_gpio_0_0/design_final_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_final_axi_gpio_0_0 || ORIG_REF_NAME==design_final_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_final/ip/design_final_xbar_0/design_final_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_final_xbar_0 || ORIG_REF_NAME==design_final_xbar_0} -quiet] -quiet

# IP: bd/design_final/ip/design_final_ps7_0_axi_periph_0/design_final_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_final_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_final_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_final/ip/design_final_rst_ps7_0_50M_0/design_final_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_final_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_final_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/design_final/ip/design_final_auto_pc_0/design_final_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_final_auto_pc_0 || ORIG_REF_NAME==design_final_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/Python/Desktop/sdup/simple_speech_recognition/project_final/project_final.gen/sources_1/bd/design_final/design_final_ooc.xdc
