# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zedboard_final.xdc

# Block Designs: bd/zedboard_pnyq_ssr/zedboard_pnyq_ssr.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_pnyq_ssr || ORIG_REF_NAME==zedboard_pnyq_ssr} -quiet] -quiet

# IP: bd/zedboard_pnyq_ssr/ip/zedboard_pnyq_ssr_processing_system7_0_1/zedboard_pnyq_ssr_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_pnyq_ssr_processing_system7_0_1 || ORIG_REF_NAME==zedboard_pnyq_ssr_processing_system7_0_1} -quiet] -quiet

# IP: bd/zedboard_pnyq_ssr/ip/zedboard_pnyq_ssr_axi_dma_0_2/zedboard_pnyq_ssr_axi_dma_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_pnyq_ssr_axi_dma_0_2 || ORIG_REF_NAME==zedboard_pnyq_ssr_axi_dma_0_2} -quiet] -quiet

# IP: bd/zedboard_pnyq_ssr/ip/zedboard_pnyq_ssr_top_ssr_0_1/zedboard_pnyq_ssr_top_ssr_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_pnyq_ssr_top_ssr_0_1 || ORIG_REF_NAME==zedboard_pnyq_ssr_top_ssr_0_1} -quiet] -quiet

# IP: bd/zedboard_pnyq_ssr/ip/zedboard_pnyq_ssr_axi_smc_2/zedboard_pnyq_ssr_axi_smc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_pnyq_ssr_axi_smc_2 || ORIG_REF_NAME==zedboard_pnyq_ssr_axi_smc_2} -quiet] -quiet

# IP: bd/zedboard_pnyq_ssr/ip/zedboard_pnyq_ssr_rst_ps7_0_20M_0/zedboard_pnyq_ssr_rst_ps7_0_20M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_pnyq_ssr_rst_ps7_0_20M_0 || ORIG_REF_NAME==zedboard_pnyq_ssr_rst_ps7_0_20M_0} -quiet] -quiet

# IP: bd/zedboard_pnyq_ssr/ip/zedboard_pnyq_ssr_xbar_0/zedboard_pnyq_ssr_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_pnyq_ssr_xbar_0 || ORIG_REF_NAME==zedboard_pnyq_ssr_xbar_0} -quiet] -quiet

# IP: bd/zedboard_pnyq_ssr/ip/zedboard_pnyq_ssr_ps7_0_axi_periph_2/zedboard_pnyq_ssr_ps7_0_axi_periph_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_pnyq_ssr_ps7_0_axi_periph_2 || ORIG_REF_NAME==zedboard_pnyq_ssr_ps7_0_axi_periph_2} -quiet] -quiet

# IP: bd/zedboard_pnyq_ssr/ip/zedboard_pnyq_ssr_auto_pc_0/zedboard_pnyq_ssr_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_pnyq_ssr_auto_pc_0 || ORIG_REF_NAME==zedboard_pnyq_ssr_auto_pc_0} -quiet] -quiet

# XDC: bd/zedboard_pnyq_ssr/zedboard_pnyq_ssr_ooc.xdc
